clean:
	rm prolific
test: prolific.c
	rm prolific
	gcc -g prolific.c -o prolific
	./prolific
prolific: prolific.c
	gcc -g prolific.c -o prolific
generation: generation.c
	gcc -g generation.c -o generation
explorer: explorer.c
	gcc -g explorer.c -o explorer
